# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

strategy:
 matrix:
  ubuntu_latest:
   imageName: 'ubuntu-latest'
   buildConfig: 'Release'
  windows_latest:
   imageName: 'windows-latest'
   buildConfig: 'ReleaseWin'
 maxParallel: 2


pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: $(buildConfig)

steps:

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: SqlAzureDacpacDeployment@1
  condition: eq( variables['buildConfiguration'], 'Release')
  inputs:
    azureSubscription: 'Visual Studio Professional Subscription(bd8db1db-4234-480d-a5ba-e4406eecfb81)'
    AuthenticationType: 'server'
    ServerName: 'TestSqlServerName'
    DatabaseName: 'TestDB'
    SqlUsername: 'admin'
    SqlPassword: 'admin'
    deployType: 'SqlTask'
    SqlFile: 'CREATE TABLE Persons (     PersonID int,     LastName varchar(255),     FirstName varchar(255),     Address varchar(255),     City varchar(255) );'
    IpDetectionMethod: 'AutoDetect'
